---
title: "Spatial Compositional Complexity"
author: "Phil"
date: "March 23, 2016"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 1
    theme: flatly
---

# Introduction

The purpose of this document is to fix notation and establish preliminary results for an approach to spatial compositional complexity measurement using logratio transforms. See [the notes](https://github.com/PhilChodrow/compositional-complexity/blob/master/methods/logratio.pdf) for a full mathematical development of the topic. 

Our goal is to test these methods on census data. 

# Analysis

## Retrieve Data

- Census data

## Clean Data

- Matrix of locations; i.e. centroids of population tracts
- Matrix of data

## Write Core Functions

- Compute objective function
- Compute row-wise entropy of data
- Compute spatial influence function values

## Implement Gradient Descent

- Consider that it may be best to use a pre-existing R package for this task, depending on how computationally intensive this turns out to be. 

## Analyze results
How did we do?
- Curves of params vs. information loss
- Consider whether there might be an appropriate normalizer for comparisons between cities or between different indicators in the same city. 
- Under what circumstances would we say that the model "fails"?

## Additional software

- Pre-processing script
- Core function definitions (as a package?) See [this](http://rmflight.github.io/posts/2014/07/analyses_as_packages.html) and [this](http://rmflight.github.io/posts/2014/07/vignetteAnalysis.html) for the why and how. 
- makefile (parameterized?)